/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Hero1 from 'components/Hero1/Hero1';
import useHome1 from 'components/Home1/useHome1';

const Property11440 = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height:
    data.currentVariant === 'Property11728'
      ? `1117px`
      : data.currentVariant === 'Property11920'
      ? `1341px`
      : `1024px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
}));

const Hero11 = styled(Hero1, {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ theme, data }) => ({
  width:
    data.currentVariant === 'Property11728'
      ? `1780.8px`
      : data.currentVariant === 'Property11920'
      ? `1978px`
      : `1484px`,
  height:
    data.currentVariant === 'Property11728'
      ? `1064.4px`
      : data.currentVariant === 'Property11920'
      ? `1182.27px`
      : `887px`,
  position: `absolute`,
  left:
    data.currentVariant === 'Property11728'
      ? `-12px`
      : data.currentVariant === 'Property11920'
      ? `-29px`
      : `-22px`,
  top:
    data.currentVariant === 'Property11728'
      ? `0px`
      : data.currentVariant === 'Property11920'
      ? `0px`
      : `-24px`,
}));

function Home1(props) {
  const { data } = useHome1();

  return (
    <Property11440 className={props.className} data={data}>
      <Hero11 data={data} />
    </Property11440>
  );
}

export default Home1;
