/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import useNavbar from 'components/Navbar/useNavbar';

const ScreenDesktop = styled('div')({
  backgroundColor: `rgba(24, 61, 184, 1)`,
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `3px 16px`,
  boxSizing: `border-box`,
  height: 'auto',
});

const Logo = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const SwdLogo = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `54px`,
  width: `166px`,
  margin: `0px`,
  overflow: `hidden`,
});

const SvgjsG1253 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `166px`,
  height: `32.75px`,
  left: `0px`,
  top: `0px`,
});

const Vector = styled('img')({
  height: `32.75px`,
  width: `166px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const SvgjsG1254 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116.2px`,
  height: `9.5px`,
  left: `25px`,
  top: `37px`,
});

const Vector1 = styled('img')({
  height: `9.5px`,
  width: `116.2px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Menu = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const CallMobile = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `35px`,
  height: `35px`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `0px`
      : data.currentVariant === 'ScreenMobile2'
      ? `0px`
      : `0px 0px 0px 30px`,
}));

const Vector2 = styled('img')({
  height: `32.98px`,
  width: `32.88px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Vector3 = styled('img')({
  height: `10.55px`,
  width: `10.56px`,
  position: `absolute`,
  left: `18px`,
  top: `6px`,
});

const Vector4 = styled('img')({
  height: `16.59px`,
  width: `16.62px`,
  position: `absolute`,
  left: `18px`,
  top: `0px`,
});

const Hamburger = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `54px`,
  height: `54px`,
  margin: `0px 0px 0px 30px`,
  overflow: `hidden`,
});

const Vector5 = styled('img')({
  height: `25px`,
  width: `36px`,
  position: `absolute`,
  left: `9px`,
  top: `16px`,
});

const Home = styled('div', {
  shouldForwardProp: (prop) => !['data'].includes(prop.toString()),
})(({ data }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `600`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin:
    data.currentVariant === 'ScreenMobile'
      ? `0px 0px 0px 30px`
      : data.currentVariant === 'ScreenMobile2'
      ? `0px 0px 0px 30px`
      : `0px`,
}));

const About = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin: `0px 0px 0px 30px`,
});

const Services = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin: `0px 0px 0px 30px`,
});

const Portfolio = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin: `0px 0px 0px 30px`,
});

const Title = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin: `0px 0px 0px 30px`,
}));

const Contact = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Hind Vadodara`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `30px`,
  textTransform: `capitalize`,
  margin: `0px 0px 0px 30px`,
}));

const CallDesktop = styled('div')({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `35px`,
  height: `35px`,
  margin: `0px 0px 0px 30px`,
});

const Vector6 = styled('img')({
  height: `32.98px`,
  width: `32.88px`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const Vector7 = styled('img')({
  height: `10.55px`,
  width: `10.56px`,
  position: `absolute`,
  left: `18px`,
  top: `6px`,
});

const Vector8 = styled('img')({
  height: `16.59px`,
  width: `16.62px`,
  position: `absolute`,
  left: `18px`,
  top: `0px`,
});

function Navbar(props) {
  const { data } = useNavbar();

  return (
    <ScreenDesktop className={props.className}>
      <Logo>
        <SwdLogo>
          <SvgjsG1253>
            <Vector
              src={`assets/images/Navbar_Vector.png`}
              loading="lazy"
              alt={'Vector'}
            />
          </SvgjsG1253>
          <SvgjsG1254>
            <Vector1
              src={`assets/images/Navbar_Vector_1.png`}
              loading="lazy"
              alt={'Vector'}
            />
          </SvgjsG1254>
        </SwdLogo>
      </Logo>
      <Menu>
        {(data.currentVariant === 'ScreenMobile' ||
          data.currentVariant === 'ScreenMobile2') && (
          <CallMobile data={data}>
            <Vector2
              src={`assets/images/Navbar_Vector_2.png`}
              loading="lazy"
              alt={'Vector'}
            />
            <Vector3
              src={`assets/images/Navbar_Vector_3.png`}
              loading="lazy"
              alt={'Vector'}
            />
            <Vector4
              src={`assets/images/Navbar_Vector_4.png`}
              loading="lazy"
              alt={'Vector'}
            />
          </CallMobile>
        )}
        {(data.currentVariant === 'ScreenMobile' ||
          data.currentVariant === 'ScreenMobile2') && (
          <Hamburger>
            <Vector5
              src={`assets/images/Navbar_Vector_5.png`}
              loading="lazy"
              alt={'Vector'}
            />
          </Hamburger>
        )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <Home data={data}>{`Home`}</Home>
          )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <About>{`About`}</About>
          )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <Services>{`Services`}</Services>
          )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <Portfolio>{`Portfolio`}</Portfolio>
          )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && <Title>{`Blog`}</Title>}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <Contact>{`Contact`}</Contact>
          )}
        {!(data.currentVariant === 'ScreenMobile') &&
          !(data.currentVariant === 'ScreenMobile2') && (
            <CallDesktop>
              <Vector6
                src={`assets/images/Navbar_Vector_6.png`}
                loading="lazy"
                alt={'Vector'}
              />
              <Vector7
                src={`assets/images/Navbar_Vector_7.png`}
                loading="lazy"
                alt={'Vector'}
              />
              <Vector8
                src={`assets/images/Navbar_Vector_8.png`}
                loading="lazy"
                alt={'Vector'}
              />
            </CallDesktop>
          )}
      </Menu>
    </ScreenDesktop>
  );
}

export default Navbar;
